apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://github.com/MatthGrand/wordpress-argocd.git'
    targetRevision: HEAD
    path: charts/wordpress
    helm:
      valueFiles:
        - values/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

